import { SignInButton, SignOutButton, SignUp, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import LayoutDesktop from "~/components/layout";
import Tables from "~/components/tables";
import TopBar from "~/components/topbar";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const { data } = api.post.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center h-full">
        <LayoutDesktop>
          <div>
            <TopBar/>
            <Tables/>
          </div>
        </LayoutDesktop>
      </main>
    </>
  );
};

export default Home;
