import { SignInButton, SignOutButton, SignUp, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Features from "~/components/features";
import Footer from "~/components/footer";
import { Header } from "~/components/header";
import GlobePage from '~/components/GlobePage/GlobePage'
import LayoutDesktop from "~/components/layout";
import Logos from "~/components/logos";
import Tables from "~/components/tables";
import Testimonials from "~/components/testimonials";
import TopBar from "~/components/topbar";

import { api } from "~/utils/api";
import Hero from "~/components/hero";

const Home: NextPage = () => {
  // const { data } = api.post.getAll.useQuery();

  // const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen h-full w-full">
          <Header/>
          <Hero/>
          <Logos/>
          <Features/>
          <Testimonials/>
          <Footer/>
      </main>
    </>
  );
};

export default Home;
