import { type NextPage } from "next";
import Head from "next/head";
import Features from "~/components/features";
import Footer from "~/components/footer";
import { Header } from "~/components/header";
import Logos from "~/components/logos";
import Testimonials from "~/components/testimonials";
import Hero from "~/components/hero";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen h-full w-full">
          <Header/>
          <Hero/>
          <Logos/>
          <Features/>
          <Testimonials/>
          <Footer/>
      </main>
    </>
  );
};

export default Home;
